image: maven:3.9-eclipse-temurin-17

stages:
  - build
  - test

build_project:
  stage: build
  script:
    - echo "正在编译项目代码..."
    - mvn clean compile
  only:
    - master
    - main
    - developing
run_tests:
  stage: test
  script:
    - echo "正在运行所有的 JUnit 单元测试..."
    - mvn test
  only:
    - master
    - main
    - developing